[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "DevLog"
pageref = "devlog"
weight = 20

[[main]]
name = "About"
pageref = "aboutme.md"
weight = 30

[[main]]
name = "Exam Portfolio"
url = "/tags/exam-portfolio/"
weight = 40

[[footer]]
none = "none"
